### ISSUE TITLE
Forslag: regel om "hvis" midt i en setning

### ISSUE THREAD

**Issue by finiteattention** [navikt/spraksjekk#1]
(Sidespalte: antar bare at vi allerede foreslår at "dersom" erstattes med "hvis" ettersom sistnevnte er enklere.)

Jeg leser mange setninger der "hvis" (det vil si noe som _kan_ gjelde leseren) står som bisetning _etter_ hovedsetningen.

Reellt eksempel:
* Du kan starte en søknad om dagpenger hvis du ønsker oversikt over hvilken dokumentasjon du må sende i din situasjon. 
Denne setningen ville vært bedre som:
* Hvis du ønsker oversikt over hvilken dokumentasjon du må sende i din situasjon, kan du starte en søknad om dagpenger.

Der "hvis"-bisetningen tar andre plass bak hovedsetningen, skjer dette:
* man må lese ganske lenge før man skjønner om setningen egentlig er relevant. Mange setninger på nav.no gjelder ikke for alle som leser. Det er dumt å kreve at brukeren fortsetter å lese setninger som så viser seg å være irrelevante.
* man får heller ikke komma (som ikke brukes når bisetningen kommer etter hovedsetningen). Komma kan være et nyttig skille for deg med lesevansker som vil ha litt bedre veiskilting for å kunne parse setningen, for eksempel å vite at disse ordene høre sammen, og disse ordene hører sammen. 

Da er forslaget mitt at vi peker til tilfeller der "Hvis" ikke står i starten av setningen. Det er ikke alltid dette vil bli aktuelt (se eksempler under) men det kan være greit å gjøre folk oppmerksom på at dette er en ting.

Eksempler der det kan være greit at "hvis" ikke kommer først i setningen:
* Du kan ha rett til AAP hvis alt dette gjelder deg: [det følger så en kulepunktliste]
* Hva hvis jeg ikke har 5 års sammenhengende medlemskap?
* Hva skjer hvis vi mangler informasjon?
* Dette kan være hvis: [kulepunktliste]

Håper dette gir mening 😅 Mener at det skal kunne implementeres som regel, men det spørs hvorvidt verktøyet burde plukke opp ting som kan være feil kontra plukke opp ting som ca. alltid vil være feil. Takker! 🙏

**Comment by eilifjohansen** [comment]
Takk for innspillet.
