### ISSUE TITLE
Forslag: regel som fanger opp implisitt "hvis" og ber om at det gjøres eksplisitt

### ISSUE THREAD

**Issue by finiteattention** [navikt/spraksjekk#2]
Norsk er litt sært (!) ettersom det ofte utelater "hvis" ved betingelsesklausul.

Eksempel 1:
* Mottar du ikke sykepenger, kan du fortsatt søke om AAP.

Det som egentlig menes er:
* Hvis du ikke mottar sykepenger, kan du fortsatt søke om AAP.

Eksempel 2:
* Har du spørsmål om utbetalinger og pengestøtte fra NAV, kan du ikke bruke dialogtjenesten i aktivitetsplanen til dette. 

Det som egentlig menes er:
* Hvis du har spørsmål om utbetalinger og pengestøtte fra NAV, kan du ikke bruke dialogtjenesten i aktivitetsplanen til dette. 

"Hvis" er et viktig ord som funker som varsling om at "nå kommer det informasjon som _kan_ være aktuell, kanskje, vi får se".

Hvis-saken er kanskje enda viktigere for utlendinger: 
- Man kan ha som morsmål et språk med helt andre mønstre og regler enn det norske "subjekt-verb-objekt" og "adverbial kommer etter hovedverb i hovedsetningen, men foran verb i bisetningen; siste brukes gjerne ved betingelsesklausul." Du som er norsk har lært deg disse reglene i barndommen om du er klar over det eller ei; utlendinger, ofte voksne, har det vanskeligere ved å lære seg nye språkregler. 
- Som følge av dette er det fullt mulig å tolke setninger med implisitt "hvis" som to separate, ikke betingete påstander: "du har spørsmål om utbetalinger og pengestøtte fra NAV, du kan ikke bruke dialogtjenesten i aktivitetsplanen til dette." Dette var et forholdsvis enkelt eksempel.
- Man har større behov for hjelp til å forstå hvilke elementer i setningen som er hvilke, og hvilke som avhenger hvilke. Her utgjør bruk av "hvis" et nyttig hjelpemiddel.

Forslag til regelen er at der vi fanger opp setninger der første ord er et bøyd verb i presens (Er, Har, Gir, …), spør vi om det kunne vært aktuelt med "Hvis …" i starten av setningen. Kunne eventuelt også brukes med preteritum (Var, Hadde, Ga, …).

Ulempen er at dette vil fange opp spørsmål som stilles:
* Er du på vei tilbake til full jobb?
* Har du behov for oppfølging?
Kanskje vi kan bygge inn i regelen at den ikke trigges når setningen inneholder et spørsmålstegn? 

Det er igjen ikke sikkert at dette alltid vil treffe, og igjen spørs det om vi heller skal lade opp verktøyet med ting som har større sannsynlighet for å treffe enn med ting som _kan_ treffe. Takk!

**Comment by eilifjohansen** [comment]
Takk for innspillet.
