### ISSUE TITLE
Mulige personopplysninger e.l.

### ISSUE THREAD

**Issue by Camulos** [navikt/spraksjekk#5]
Kunne det være en ide å legge inn MOD11-sjekk dersom det er 11 siffer i serier (11-serie, eller 6+5-serie) som kan være fødselsnummer og advare om personopplysninger på bakgrunn av fødselsnummer og ikke telefonnummer i de tilfellene?

**Comment by eilifjohansen** [comment]
Hei, dette var en god ide. Dette kan vi få på plass.

**Comment by eilifjohansen** [comment]
Sjekk for fødselsnummer i Klarspåkshjelpen har nå blitt lagt til :-)
