### ISSUE TITLE
Ser ut som sjekk av lengde på tekst har en feil

### ISSUE THREAD

**Issue by eklem** [navikt/spraksjekk#7]
Får feilmelding "For lite tekst" på `Liks`-sjekken når jeg ikke har punktum, men fungerer fint hvis du legger til et punktum på setningen:

```text
Finn ut hvor lett det er å lese teksten din
```

![Screenshot 2023-12-13 at 11 25 12](https://github.com/navikt/spraksjekk/assets/236656/63b0452e-13c6-4e19-8862-01d584ebaa8e)
![Screenshot 2023-12-13 at 11 26 20](https://github.com/navikt/spraksjekk/assets/236656/f883fc97-47a9-4114-8326-7edcc8869b36)

**Comment by eilifjohansen** [comment]
Hei, dette kommer av at LIX regneren krever at man minst har en komplett setning. Når du legger til et . (punktum) blir setningen komplett, da vil den gjøre beregningen for deg :-)
